/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  Resume,  Story } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "ExtractResume" BAML action.
 *
 * This server action calls the underlying BAML function "ExtractResume"
 * with the specified parameters.
 *
 * @param { string } resume - Input parameter.
 *
 * @returns {Promise<Resume>} A promise that resolves with the result of the action.
 */
export const ExtractResume = async (
  resume: string,
): Promise<Resume> => {
  return b.ExtractResume(
    resume,
  );
};

/**
 * Executes the "WriteMeAStory" BAML action.
 *
 * This server action calls the underlying BAML function "WriteMeAStory"
 * with the specified parameters.
 *
 * @param { string } input - Input parameter.
 *
 * @returns {Promise<Story>} A promise that resolves with the result of the action.
 */
export const WriteMeAStory = async (
  input: string,
): Promise<Story> => {
  return b.WriteMeAStory(
    input,
  );
};